name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/wosnxn123/android_kernel_xiaomi_sdm660
          kernel-branch: lineage-20.0
          config: clover_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 12
          clang-url: https://github.com/Mandi-Sa/clang/releases/download/amd64-kernel-arm_static-21/llvm21.0.0-binutils2.43.1_amd64-kernel-arm_static-20250223.7z
